FROM glowtest.azurecr.io/builder AS builder
WORKDIR /go/src/app/
COPY ./  /go/src/app/
RUN go get
RUN GOOS=linux CGO_ENABLED=0 go build -o app .

FROM alpine
COPY --from=builder /go/src/app/app /app
ENTRYPOINT [ "/app" ]