version: 2
jobs:
   build:
     working_directory: /go/src/github.com/JacobSieberg/golang-CI-tests
     docker:
       - image: circleci/golang:1.9-alpine3.6
     steps:
       - checkout
       - run: apk update
       - run: apk add git
       - run: apk add gcc
       - run: apk add musl-dev
       - run: go get github.com/alecthomas/gometalinter
       - run: go get -u github.com/jstemmer/go-junit-report
       - run: go get -u github.com/360EntSecGroup-Skylar/goreporter
       - run: gometalinter --install