version: 2
jobs:
   build:
     working_directory: /go/src/github.com/JacobSieberg/golang-CI-tests
     docker:
       - image: glowtest.azurecr.io/builder
         auth:
           username: $CR_NAME
           password: $CR_PASS
     steps:
       - checkout
       - setup_remote_docker
       - run:
          name: Build docker images
          command: |
            for D in `find test/cmd/* -type d`
            do
              DNAME=$(basename $D)
              if echo "$CIRCLE_TAG" | grep -q "^$DNAME:"; then
                docker build -t $CR_URI/$CIRCLE_TAG test/cmd/$DNAME/
              else 
                docker build test/cmd/$DNAME
              fi
            done
       - deploy:
          name: Push docker images
          command: |
            for D in `find test/cmd/* -type d`
            do
              DNAME=$(basename $D)
              if echo "$CIRCLE_TAG" | grep -q "^$DNAME:"; then
                docker login $CR_URI -u $CR_NAME -p $CR_PASS              
                docker push $CR_URI/$CIRCLE_TAG
              fi
            done
       - deploy:
          name: Deploy to kubernetes
          command: |
            if [ -z $CIRCLE_TAG ]; then
              az login --service-principal -u $AZURE_USER -p $AZURE_SECRET --tenant $AZURE_TENANT
              az aks get-credentials -n $AKS_NAME -g $AKS_GROUP
              for D in `find test/cmd/* -type d`
              do
                DNAME=$(basename $D)
                if echo "$CIRCLE_TAG" | grep -q "^$DNAME:"; then
                  IMAGE=$CIRCLE_TAG mo $(find k8s/$DNAME/*) | kubectl apply -f -
                  kubectl rollout status deployment/$DNAME
                fi
                done
            fi