version: 2
jobs:
   build:
     working_directory: /go/src/github.com/JacobSieberg/golang-CI-tests
     docker:
       - image: glowtest.azurecr.io/builder
         auth:
           username: $CR_NAME
           password: $CR_PASS
     steps:
       - checkout
       - setup_remote_docker
       - run: docker login $CR_URI -u $CR_NAME -p $CR_PASS
       - run: docker build -t glowtest.azurecr.io/test-app:$CIRCLE_BUILD_NUM ./test/cmd/test/
       - run: docker push glowtest.azurecr.io/test-app:$CIRCLE_BUILD_NUM
       - run: az login --service-principal -u $AZURE_USER -p $AZURE_SECRET --tenant $AZURE_TENANT
       - run: az aks get-credentials -n $AKS_NAME -g $AKS_GROUP
       - run: VERSION=$CIRCLE_BUILD_NUM cat k8s/dep.yaml | mo | kubectl apply -f -
       - run: cat k8s/ser.yaml | mo | kubectl apply -f -
      #  - run: kubectl set image deployment/test-app test-app=glowtest.azurecr.io/test-app:$CIRCLE_BUILD_NUM
       - run: kubectl rollout status deployment/test-app