version: 2
jobs:
   build:
     working_directory: /go/src/github.com/JacobSieberg/golang-CI-tests
     docker:
       - image: golang:1.9-alpine3.6
     steps:
       - checkout
       - run: 
           name: Setup
           command: |
             apk update
             apk add git
             apk add gcc
             apk add musl-dev
             go get github.com/alecthomas/gometalinter
             go get -u github.com/jstemmer/go-junit-report
             go get -u github.com/360EntSecGroup-Skylar/goreporter
             gometalinter --install
           when: always
       - run: gometalinter ./test/... > /go/src/github.com/JacobSieberg/golang-CI-tests/lint-results.txt
       - store_artifacts:
          path: /go/src/github.com/JacobSieberg/golang-CI-tests/lint-results.txt
          destination: lint-results.txt
       - run: 
           name: Test
           command: |
             for fn in `go list ./test/...`; do
               go test -v -coverprofile=c.out $fn >> test.txt;
               if [ ! -f c.out ]; then
                continue; 
              fi;
              cat c.out >> cover.out;
              rm -f c.out ;
              done;
              touch coverage.html;
              if [ -f cover.out ]; then 
                awk '!seen[$0]++' cover.out>covertrimmed.out;
                go tool cover -html=covertrimmed.out -o=coverage.html;
              fi;
              cat test.txt | go-junit-report > report.xml
           when: always
       - store_artifacts:
          path: /go/src/github.com/JacobSieberg/golang-CI-tests/coverage.html
          destination: coverage.html
       - store_test_results:
          path: /go/src/github.com/JacobSieberg/golang-CI-tests
       - store_artifacts:
          path: /go/src/github.com/JacobSieberg/golang-CI-tests/test.txt
          destination: test_results.txt
       - store_artifacts:
          path: /go/src/github.com/JacobSieberg/golang-CI-tests/coverage.html
          destination: coverage.html
       - store_test_results:
          path: /go/src/github.com/JacobSieberg/golang-CI-tests
       - store_artifacts:
          path: /go/src/github.com/JacobSieberg/golang-CI-tests/test.txt
          destination: test_results.txt
       - run: 
          name: Build binaries
          command: |
            start=`date +%s`    
            (
                echo "Building for windows amd64"
                GOOS=windows GOARCH=amd64 go build -o binaries/test-windows.amd64.exe ./test/cmd/test
                echo "Finished windows amd64"
            ) &
            (
                echo "Building for linux amd64"
                GOOS=linux GOARCH=amd64 go build -o  binaries/test-linux.amd64 ./test/cmd/test
                echo "Finished linux amd64"
            ) &
            (
                echo "Building for linux arm"
                GOOS=linux GOARCH=arm go build -o  binaries/test-linux.arm ./test/cmd/test
                echo "Finished linux arm"
            ) &
            wait
            end=`date +%s`
            echo took $((end-start)) seconds
            echo "Done"
          when: always
       - store_artifacts:
          path: /go/src/github.com/JacobSieberg/golang-CI-tests/binaries
          destination: binaries