version: 2
jobs:
   build:
     working_directory: /go/src/github.com/JacobSieberg/golang-CI-tests
     docker:
       - image: glowtest.azurecr.io/builder
         auth:
           username: $CR_NAME
           password: $CR_PASS
     steps:
       - checkout
       - setup_remote_docker
       - run: 
          name: Setup
          command: |
            mkdir output
            dep ensure
          when: always
       - run:
          name: Build
          command: |
            docker build -t $CR_URI/test-app:$CIRCLE_BUILD_NUM
       - deploy:
          name: Push
          command: |
            docker login $CR_URI -u $CR_NAME -p $CR_PASS
            docker push glowtest.azurecr.io/test-app:$CIRCLE_BUILD_NUM
       - deploy:
          name: Deploy to kubernetes
          command: |
            az login --service-principal -u $AZURE_USER -p $AZURE_SECRET --tenant $AZURE_TENANT
            az aks get-credentials -n $AKS_NAME -g $AKS_GROUP
            cat k8s/dep.yaml | VERSION=$CIRCLE_BUILD_NUM mo | kubectl apply -f -
            cat k8s/ser.yaml | mo | kubectl apply -f -
            kubectl rollout status deployment/test-app