version: 2
jobs:
   build:
     working_directory: /go/src/github.com/JacobSieberg/golang-CI-tests
     docker:
       - image: glowtest.azurecr.io/builder
         auth:
           username: $CR_NAME
           password: $CR_PASS
     steps:
       - checkout
       - setup_remote_docker
       - run: 
          name: Setup
          command: |
            mkdir output
            dep ensure
          when: always
       - run:
          name: Build binaries
          command: |
            for D in `find test/cmd -type d`
            do
              DNAME=$(basename $D)
              GOOS=linux GOARCH=amd64 go build test/cmd/$D/ -o output/$DNAME/app
            done
       - run:
          name: Build docker containers
          command: |
            for D in `find docker -type d`
            do
              DNAME=$(basename $D)
              cp output/$DNAME/app $D/app
              docker build -t $CR_URI/$DNAME:$CIRCLE_BUILD_NUM $D
            done
       - deploy:
          name: Push docker images
          command: |
            docker login $CR_URI -u $CR_NAME -p $CR_PASS
            for D in `find docker -type d -printf '%f\n'`
            do
              docker push -t $CR_URI/$D:$CIRCLE_BUILD_NUM
            done
       - deploy:
          name: Deploy to kubernetes
          command: |
            az login --service-principal -u $AZURE_USER -p $AZURE_SECRET --tenant $AZURE_TENANT
            az aks get-credentials -n $AKS_NAME -g $AKS_GROUP
            cat k8s/dep.yaml | VERSION=$CIRCLE_BUILD_NUM mo | kubectl apply -f -
            cat k8s/ser.yaml | mo | kubectl apply -f -
            kubectl rollout status deployment/test-app