version: 2
jobs:
   build:
     working_directory: /go/src/github.com/JacobSieberg/golang-CI-tests
     docker:
       - image: glowtest.azurecr.io/builder
         auth:
           username: $CR_NAME
           password: $CR_PASS
     steps:
       - checkout
       - setup_remote_docker
       - run: docker login $CR_URI -u $CR_NAME -p $CR_PASS
       - run: docker build -t glowtest.azurecr.io/test-app ./test/cmd/test/
       - run: docker push glowtest.azurecr.io/test-app