apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image:  glowtest.azurecr.io/test-app
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: glowtest
