apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service-name
  labels:
    app: service-name
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: service-name
  template:
    metadata:
      labels:
        app: service-name
    spec:
      containers:
      - name: service-name
        image:  glowtest.azurecr.io/{{IMAGE}}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: glowtest
